language: python

cache:
  directories:
  - "~/.platformio"

install:
- pip install -U platformio
- platformio update
- platformio lib -g install 1

env:
- BOARD=esp12e

script:
  - "echo $PWD"
  - "echo $HOME"
  - pio lib install https://github.com/jaycollett/UltimateFoosball.git
  - pio lib install "PubSubClient"
  - pio lib install "FastLED"
  - pio lib install "Adafruit_VS1053"
  - pio lib install "Adafruit_LEDBackpack"
  - pio lib install "SD"
  - pio lib install "SPI"
  - platformio ci --board=$BOARD --lib=$PWD/ArduinoCode $PWD/ArduinoCode/UltimateFoosball/UltimateFoosball.ino
  
notifications:
  email:
    on_success: change
    on_failure: change