language: python

cache:
  directories:
  - "~/.platformio"

install:
- pip install -U platformio
- platformio update
- platformio lib -g install 1

env:
- PLATFORM=atmelsam
- BOARD=adafruit_feather_m0

script:
  - "echo $PWD"
  - "echo $HOME"
  - pio lib install https://github.com/jaycollett/UltimateFoosball.git
  - pio lib install "PubSubClient"
  - pio lib install "FastLED"
  - pio lib install "adafruit/Adafruit VS1053 Library@^1.2.0"
  - pio lib install "Adafruit_LEDBackpack"
  - pio lib install "SD"
  - pio lib install "adafruit/Adafruit GFX Library@^1.10.4"
  - platformio ci --board=$BOARD --lib=$PWD/ArduinoCode $PWD/ArduinoCode/UltimateFoosball/UltimateFoosball.ino
  
notifications:
  email:
    on_success: change
    on_failure: change
